// freeze-source.ts — the two edits that freeze a module, done deterministically.
//
// WHY THIS EXISTS. The freeze is the one deploy in this system that can never be
// repeated, corrected, or rolled back, and until now it was the ONLY deploy with
// no tooling: `build-tx.ts` had 21 steps and not one of them was `freeze`. The
// only artifact in the repo that performed the two edits was a TEST FIXTURE
// generator. So the permanent, final, unrepeatable deploy was a hand edit under
// ceremony pressure, while every reversible step was tooled and deterministic.
//
// THE TWO EDITS, and why both are mandatory:
//
//   1. FROZEN-MODULE false -> true. The one-way door.
//
//   2. (bless "<currently deployed hash>"). Flipping the constant CHANGES the
//      module hash. Two things pin the old hash and break without the bless:
//        * an in-flight `transfer-crosschain` - step 0 done, step 1 pending -
//          resumes against the hash it started under. Unblessed, it can NEVER
//          resume: the tokens are debited on the source chain and uncreditable
//          on the target, forever. There is no rollback for step 1.
//        * `pco-claim` pins `pco`'s hash. An unblessed `pco` freeze makes every
//          claim, grant and `set-open` fail with "hash not blessed" - including
//          the master kill switch.
//
// The hash MUST come from the chain (`(at 'hash (describe-module ...))`), never
// from a local recomputation: what has to be blessed is what is actually
// deployed, and the whole point of the ceremony is to stop assuming those agree.
//
// The output is written back into contracts/ and COMMITTED. That is not
// housekeeping: `verify-deployed` byte-compares deployed code against the repo,
// so from the instant of the freeze it would report DIFFERS for `pco` forever
// unless the frozen source is what the repo holds. The "verify it yourself"
// story in docs/VERIFYING.md would break at exactly the moment the system
// reached its intended permanent state.

export const FREEZE_MARKER =
  ';; FROZEN. Generated by `build-tx.ts freeze` - see ops/src/freeze-source.ts.';

export type FrozenResult = { source: string; blessed: string[] };

/**
 * Apply the two freeze edits to a module source.
 *
 * @param src     the module source, exactly as deployed
 * @param hashes  EVERY module hash that must remain resolvable after the freeze:
 *                the one currently deployed (from describe-module), plus every
 *                previously deployed hash still reachable by an in-flight
 *                cross-chain defpact. Pass them all; a bless costs nothing and a
 *                missing one strands tokens permanently.
 */
export function freezeSource(src: string, hashes: string | string[]): FrozenResult {
  const list = [...new Set(typeof hashes === 'string' ? [hashes] : hashes)];
  if (list.length === 0) {
    throw new Error('refusing to freeze: no hash to bless was supplied');
  }
  // A malformed hash is rejected by Pact at LOAD time, which on a freeze deploy
  // means discovering it after signing with three hardware wallets. Check the
  // shape here: Pact module hashes are 43-char unpadded base64url (32 bytes).
  for (const hash of list) {
    if (!/^[A-Za-z0-9_-]{43}$/.test(hash)) {
      throw new Error(
        `refusing to freeze: "${hash}" is not a 43-char base64url module hash. ` +
        `Read it from the chain with (at 'hash (describe-module "<ns>.<module>")).`,
      );
    }
  }

  const anchor = /^(\s*)\(defconst FROZEN-MODULE:bool false/m;
  const m = src.match(anchor);
  if (!m) {
    throw new Error(
      'refusing to freeze: could not find `(defconst FROZEN-MODULE:bool false`. ' +
      'Either the module is already frozen or the constant was renamed.',
    );
  }
  if (/\(bless\s/.test(src)) {
    throw new Error(
      'refusing to freeze: the source already contains a (bless ...) form. ' +
      'Freezing an already-frozen or already-blessed source needs a human decision ' +
      'about which hashes must remain blessed.',
    );
  }

  const indent = m[1].replace(/\n/g, '');
  const insert =
    `${indent}${FREEZE_MARKER}\n` +
    list.map((h) => `${indent}(bless "${h}")\n`).join('') + '\n';

  // Insert immediately before the defconst line, preserving its own leading blank
  // structure, then flip the flag.
  const at = m.index! + (m[1].startsWith('\n') ? 1 : 0);
  let out = src.slice(0, at) + insert + src.slice(at);
  out = out.replace('FROZEN-MODULE:bool false', 'FROZEN-MODULE:bool true');

  // Post-conditions, asserted rather than assumed: this output is about to be
  // signed by three hardware wallets and deployed permanently.
  if (!/\(defconst FROZEN-MODULE:bool true/.test(out)) {
    throw new Error('freeze transform failed: the flag was not flipped');
  }
  for (const h of list) {
    if (!out.includes(`(bless "${h}")`)) {
      throw new Error(`freeze transform failed: (bless "${h}") was not inserted`);
    }
  }
  if (/FROZEN-MODULE:bool false/.test(out)) {
    throw new Error('freeze transform failed: a `false` flag survived the flip');
  }
  // Exactly two edits and nothing else. Anything beyond the inserted lines and
  // the one flipped word means the transform touched code it was not asked to.
  const stripped = out
    .replace(insert, '')
    .replace('FROZEN-MODULE:bool true', 'FROZEN-MODULE:bool false');
  if (stripped !== src) {
    throw new Error(
      'freeze transform failed: the output differs from the input by more than ' +
      'the bless insertion and the flag flip',
    );
  }
  return { source: out, blessed: list };
}
