// freeze-source.ts — the two edits that freeze a module, done deterministically.
//
// WHY THIS EXISTS. The freeze is the one deploy in this system that can never be
// repeated, corrected, or rolled back, and until now it was the ONLY deploy with
// no tooling: `build-tx.ts` had 21 steps and not one of them was `freeze`. The
// only artifact in the repo that performed the two edits was a TEST FIXTURE
// generator. So the permanent, final, unrepeatable deploy was a hand edit under
// ceremony pressure, while every reversible step was tooled and deterministic.
//
// THE TWO EDITS, and why both are mandatory:
//
//   1. FROZEN-MODULE false -> true. The one-way door.
//
//   2. (bless "<currently deployed hash>"). Flipping the constant CHANGES the
//      module hash. Two things pin the old hash and break without the bless:
//        * an in-flight `transfer-crosschain` - step 0 done, step 1 pending -
//          resumes against the hash it started under. Unblessed, it can NEVER
//          resume: the tokens are debited on the source chain and uncreditable
//          on the target, forever. There is no rollback for step 1.
//        * `pco-claim` pins `pco`'s hash. An unblessed `pco` freeze makes every
//          claim, grant and `set-open` fail with "hash not blessed" - including
//          the master kill switch.
//
// The hash MUST come from the chain (`(at 'hash (describe-module ...))`), never
// from a local recomputation: what has to be blessed is what is actually
// deployed, and the whole point of the ceremony is to stop assuming those agree.
//
// The output is written back into contracts/ and COMMITTED. That is not
// housekeeping: `verify-deployed` byte-compares deployed code against the repo,
// so from the instant of the freeze it would report DIFFERS for `pco` forever
// unless the frozen source is what the repo holds. The "verify it yourself"
// story in docs/VERIFYING.md would break at exactly the moment the system
// reached its intended permanent state.

export const FREEZE_MARKER =
  ';; FROZEN. Generated by `build-tx.ts freeze` - see ops/src/freeze-source.ts.';

/**
 * Modules whose hash is PINNED by something, and which therefore must bless the
 * deployed hash before any upgrade. Measured, that is `pco` alone: it owns the
 * only cross-chain defpact (which carries the hash it yielded under, and whose
 * step 1 has no rollback) and both other modules depend on it. Nothing depends on
 * `pco-claim` or `pco-gas-station` and neither defines a defpact, so an unblessed
 * redeploy of those strands nothing — requiring a bless there made the sanctioned
 * freeze order literally unbuildable.
 *
 * Exported so `build-tx` (which gates the upgrade build) and `verify-deployed`
 * (which checks the bless against what is actually on chain) cannot disagree.
 */
export const NEEDS_BLESS: ReadonlySet<string> = new Set(['pco']);

export type FrozenResult = { source: string; blessed: string[] };

/**
 * Apply the two freeze edits to a module source.
 *
 * @param src     the module source, exactly as deployed
 * @param hashes  EVERY module hash that must remain resolvable after the freeze:
 *                the one currently deployed (from describe-module), plus every
 *                previously deployed hash still reachable by an in-flight
 *                cross-chain defpact. Pass them all; a bless costs nothing and a
 *                missing one strands tokens permanently. Hashes the source
 *                already blesses are added automatically - forgetting one of
 *                those is not a failure mode this tool leaves open.
 *
 * @returns       `blessed` is the UNION of the source's existing bless forms and
 *                the supplied hashes; `source` is guaranteed to bless every one.
 */
export function freezeSource(src: string, hashes: string | string[]): FrozenResult {
  const supplied = [...new Set(typeof hashes === 'string' ? [hashes] : hashes)];
  if (supplied.length === 0) {
    throw new Error('refusing to freeze: no hash to bless was supplied');
  }
  // Hashes the source ALREADY blesses. Since the chain-local voting design (C1) `pco.pact` carries
  // a permanent bless of its predecessor, and every upgrade appends another, so
  // "the source has no bless" stopped being true and cannot be a precondition.
  //
  // These are CARRIED FORWARD, never dropped. Each one records a hash something
  // may still pin - a dependent between the two deploys of a two-step upgrade, or
  // an in-flight `transfer-crosschain` whose step 1 has no rollback. Dropping one
  // at the single moment the module becomes unchangeable forever is precisely the
  // unrecoverable failure this file exists to prevent, and there is no quorum that
  // repairs it afterwards. A bless costs nothing; a missing one is permanent.
  const already = [...src.matchAll(/\(bless\s+"([^"]*)"\s*\)/g)].map((m) => m[1]);
  const list = [...new Set([...already, ...supplied])];
  // A malformed hash is rejected by Pact at LOAD time, which on a freeze deploy
  // means discovering it after signing with three hardware wallets. Check the
  // shape here: Pact module hashes are 43-char unpadded base64url (32 bytes).
  for (const hash of list) {
    if (!/^[A-Za-z0-9_-]{43}$/.test(hash)) {
      throw new Error(
        `refusing to freeze: "${hash}" is not a 43-char base64url module hash. ` +
        `Read it from the chain with (at 'hash (describe-module "<ns>.<module>")).`,
      );
    }
  }

  const anchor = /^(\s*)\(defconst FROZEN-MODULE:bool false/m;
  const m = src.match(anchor);
  if (!m) {
    throw new Error(
      'refusing to freeze: could not find `(defconst FROZEN-MODULE:bool false`. ' +
      'Either the module is already frozen or the constant was renamed.',
    );
  }
  if (/\(defconst FROZEN-MODULE:bool true/.test(src)) {
    throw new Error(
      'refusing to freeze: the source is already frozen. Re-running the freeze ' +
      'transform on frozen source would insert a second bless block.',
    );
  }

  const indent = m[1].replace(/\n/g, '');
  // Insert only the hashes not already blessed. The existing (bless ...) forms
  // stay exactly where they are, which is what keeps the "changes nothing else"
  // post-condition below meaningful - the transform never rewrites them.
  const fresh = list.filter((h) => !already.includes(h));
  const insert = fresh.length === 0 ? '' :
    `${indent}${FREEZE_MARKER}\n` +
    fresh.map((h) => `${indent}(bless "${h}")\n`).join('') + '\n';

  // Insert immediately before the defconst line, preserving its own leading blank
  // structure, then flip the flag.
  const at = m.index! + (m[1].startsWith('\n') ? 1 : 0);
  let out = src.slice(0, at) + insert + src.slice(at);
  out = out.replace('FROZEN-MODULE:bool false', 'FROZEN-MODULE:bool true');

  // Post-conditions, asserted rather than assumed: this output is about to be
  // signed by three hardware wallets and deployed permanently.
  if (!/\(defconst FROZEN-MODULE:bool true/.test(out)) {
    throw new Error('freeze transform failed: the flag was not flipped');
  }
  // `list` is the UNION of what the source already blessed and what the caller
  // supplied, so this loop is also the check that no pre-existing bless was lost:
  // the one failure here that no later deploy could repair.
  for (const h of list) {
    if (!out.includes(`(bless "${h}")`)) {
      throw new Error(`freeze transform failed: (bless "${h}") is not in the output`);
    }
  }
  if (/FROZEN-MODULE:bool false/.test(out)) {
    throw new Error('freeze transform failed: a `false` flag survived the flip');
  }
  // Exactly two edits and nothing else. Anything beyond the inserted lines and
  // the one flipped word means the transform touched code it was not asked to.
  const stripped = out
    .replace(insert, '')
    .replace('FROZEN-MODULE:bool true', 'FROZEN-MODULE:bool false');
  if (stripped !== src) {
    throw new Error(
      'freeze transform failed: the output differs from the input by more than ' +
      'the bless insertion and the flag flip',
    );
  }
  return { source: out, blessed: list };
}
